pipeline {
    agent any
    tools {
        gradle "Gradle-3.4"
    }
    stages {
        stage('Cleanup Workspace - Master') {
            agent any
            steps {
                echo 'Cleaning workspace....'
                cleanWs()
            }
        }
        stage('Checkout') {
            agent any
            steps {
                git branch: 'test-branch', url: 'https://github.com/navegit/testproj.git'
                sh 'gradle clean build'
                sleep 15
            }
        }
        stage('Build workspace') {
            steps {
              echo "stashing"
              stash name: "app", includes: "app/build/libs/*.jar"
              sleep 30
            }
        }
        stage('Cleanup Workspace') {
            steps {
                echo 'Cleaning workspace....'
                cleanWs()
            }
        }
        stage('Deploy Workspace') {
            steps {
               unstash "app"
               sleep 30
            }
        }
    }
}