pipeline {
  agent none
  tools {
     maven 'Maven-3.5.4'
  }
  parameters {
      // create a job parameter for this pipeline with a default
      booleanParam(defaultValue: false, description: 'Simulate the promotion', name: 'SIMUL')
  }
  stages {
    /*
    stage('Stage: when') {
    	when {
    		branch 'master'
    	}
    }
    */
    stage('Stage: when') {
       when {
          expression {
              // only run when the expression is true
              currentBuild.getNumber() % 2 == 1
          }
       }
       steps {
          // call the current job and pass the SIMUL parameter value
          build job: currentBuild.getProjectName(), parameters: [
              booleanParam(name: 'SIMUL', value: params.SIMUL)
          ]
       }
    }
  }
  post {
    always {
      echo "I ALWAYS run firsts"
    }
    unstable {
      echo "UNSTABLE runs after ALWAYS"
    }
  }
}