pipeline {
  agent none

  stages {
    stage("Hello") {
       input{
       		message "Press Ok to continue"
       		submitter "user1,user2"
       		parameters {
       			string(name:'username', defaultValue: 'user', description: 'Username of the user pressing Ok')
       		}
       }
      steps {
        echo "hello"
        // need to use script block to assign value
        script {
          echo "HOW R U"
        }
      }
    }
    stage('Run Tests') {
        parallel {
            stage('Unit Test') {
                steps {
                  sh "echo 'running test'"
                }
            }
            stage('Integration test Test On Linux') {
                steps {
                  sh "echo 'running integration'"
                }
            }
        }
    }

  }
  post {
    always {
      echo "I ALWAYS run firsts"
    }
    unstable {
      echo "UNSTABLE runs after ALWAYS"
    }
  }
}