pipeline {
  agent none
  tools {
     maven 'Maven-3.5.4'
  }
  stages {
    stage("Hello") {
       echo "running stage"
       steps {
           echo "hello"
           // need to use script block to assign value
           script {
             echo "HOW R U"
           }
       }
      /*
      input{
            message "Press Ok to continue"
            submitter "user1,user2"
            parameters {
                string(name:'username', defaultValue: 'user', description: 'Username of the user pressing Ok')
            }
      }
      */

    }
    stage('Run Tests') {
        parallel {
            stage('Unit Test') {
                steps {
                  echo "running test"
                  sleep 10
                  script {
                    echo "Scripted block"
                    env.NODE_ENV = "test"
                    print "Environment will be : ${env.NODE_ENV}"
                  }
                }
            }
            stage('Integration test Test On Linux') {
                steps {
                  echo "running integration"
                  sleep 5
                }
            }
        }
    }

  }
  post {
    always {
      echo "I ALWAYS run firsts"
    }
    unstable {
      echo "UNSTABLE runs after ALWAYS"
    }
  }
}