pipeline {
    agent any
    stages {
        stage('Stash') {
            steps {
                //sh "mkdir -p output"

                // Write a text file there.
                //writeFile file: "output/somefile", text: "Hey look, some text."

                // Stash that directory and file.
                // Note that the includes could be "output/", "output/*" as below, or even
                // "output/**/*" - it all works out basically the same.
                dir('my-dir'){
                  git branch: 'master', url: 'https://github.com/navegit/testproj.git'
                }
                stash name: "first-stash", includes: "my-dir/*"
                sleep 60
            }
        }
        stage('Unstash') {
            steps {
                dir("first-stash") {
                        unstash "first-stash"
                }
                sleep 60
            }
        }
    }
}